### ISSUE TITLE
Handle record deletion

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-swh#28]
When a record is deleted from InvenioRDM, we should notify Software Heritage.

**Comment by moranegg** [comment]
Record will not be deleted from SWH due to deletion on InvenioRDM (or other Infrstructure).
no need to inform SWH :)

If you want to inform the user, you can use:
https://www.softwareheritage.org/legal/content-policy/

**Comment by alejandromumo** [comment]
I am closing the issue since SWH doesn't need to be notified.

Thanks @moranegg !
